# Generated by Django 3.1.12 on 2025-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_job_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
