# Generated by Django 3.1.12 on 2025-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250920_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='about',
            field=models.TextField(blank=True, help_text='Tell us about yourself, your career goals, and what makes you unique'),
        ),
    ]
