services:
  - type: web
    name: jport-portal
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir job job.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"